on:
  pull_request_target:

name: test1-pull-request-target

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello world! from pull request target"
    - run: echo "${{ github.head_ref }}"
    - run: echo "${{ github.ref }}"
    
